apiVersion: v1
kind: Service
metadata: 
   name: backend
   labels:
        app: studend-back-svc
spec:
   type: LoadBalancer
   ports:
      - port: 3000
        targetPort: 3000
   selector: 
          app: student-back

