kind: Pod
apiVersion: v1
metadata:
        name: mysamplepod
spec:
   containers:
          - name: mysamplepod
            image: nginx
            volumeMounts:
                    - mountPath: "/mnt/azure"
                      name: volume
   volumes:
           - name: volume
             persistentVolumeClaim:
                     claimName: azure-managed-disk 
