apiVersion: apps/v1
kind: Deployment
metadata:
  name:  nginx-front
spec:
      replicas: 3
      selector:
          matchLabels:
                app: myapp
      template:
        metadata:
          labels:
             app: myapp
        spec:
         containers:
            - name: myapp-nginx
              image: nginx:1.7.1
